# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medi_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('product_price', models.IntegerField()),
                ('confirmation_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
